sites-enabled/03-all-guide.org.conf
=> fix: guide redirects permanently

sites-enabled/10-www.freecodecamp.org.conf, sites-enabled/15-chinese.freecodecamp.org.conf, sites-enabled/20-www.freecodecamp.dev.conf, sites-enabled/30-chinese.freecodecamp.dev.conf
Refers: https://forum.freecodecamp.org/t/446973
=> fix: health check endpoint should be exact match

sites-enabled/10-www.freecodecamp.org.conf, sites-enabled/20-www.freecodecamp.dev.conf
This PR creates the routing for /chinese-traditional
=> feat: enable chinese traditional

sites-enabled/10-www.freecodecamp.org.conf, sites-enabled/20-www.freecodecamp.dev.conf
Checklist:
It seems reasonable to start by caching the fonts since they never change and if something goes wrong, it doesn't break any functionality.
=> feat: add cache headers for fonts

sites-enabled/10-www.freecodecamp.org.conf, sites-enabled/15-chinese.freecodecamp.org.conf, sites-enabled/20-www.freecodecamp.dev.conf, sites-enabled/30-chinese.freecodecamp.dev.conf
Checklist:
Fixes chinese-traditional, extends the caching to chinese.freecodecamp.dev and chinese.freecodecamp.org
=> feat: update chinese

sites-enabled/10-www.freecodecamp.org.conf, sites-enabled/20-www.freecodecamp.dev.conf
=> fix: temporarily redirect it news and forum to eng

sites-enabled/10-www.freecodecamp.org.conf, sites-enabled/20-www.freecodecamp.dev.conf
Removes the last attempt and replaces it with simple 302 redirects
=> feat: add temp redirects to english /news

sites-enabled/10-www.freecodecamp.org.conf, sites-enabled/20-www.freecodecamp.dev.conf
This PR will enable news for Portuguese
=> feat(news): enable routing to portuguese news

sites-enabled/10-www.freecodecamp.org.conf, sites-enabled/20-www.freecodecamp.dev.conf
=> feat(news): enable routing to italian news

sites-enabled/10-www.freecodecamp.org.conf, sites-enabled/15-chinese.freecodecamp.org.conf, sites-enabled/20-www.freecodecamp.dev.conf, sites-enabled/21-api.freecodecamp.dev.conf, sites-enabled/30-chinese.freecodecamp.dev.conf, snippets/common/add-noindex-headers.conf
Closes https://github.com/freeCodeCamp/news/issues/76
=> fix(news): proxy to JAMStack apps

sites-enabled/10-www.freecodecamp.org.conf, sites-enabled/15-chinese.freecodecamp.org.conf
This enables the JAMStack news for Chinese, Portuguese & Espanol
=> feat(news): enable JAMStack for chinese, portuguese & espanol

sites-enabled/10-www.freecodecamp.org.conf
While this is good to go - this is waiting on the ads feature to work, and confirming some more stability issues we have with the cache.
=> feat(news): enable JAMStack for english

sites-enabled/10-www.freecodecamp.org.conf, sites-enabled/20-www.freecodecamp.dev.conf
This PR creates the config to start using JAMstack news for Arabic
=> feat: enable Arabic news - JAMstack

sites-enabled/10-www.freecodecamp.org.conf
This PR enables several new publication instances. This is to be fast-forwared.
=> feat: create new publications

sites-enabled/10-www.freecodecamp.org.conf
Checklist:
This PR enables new publication instances for Vietnamese and Indonesian.
=> feat: enable Vietnamese and Indonesian news - JAMstack

sites-enabled/10-www.freecodecamp.org.conf
Lots of typos went in, which need to be fixed.
Reverts freeCodeCamp/nginx-config#67
cc @zairahira
=> revert "feat: enable Vietnamese and Indonesian news - JAMstack"

sites-enabled/10-www.freecodecamp.org.conf, sites-enabled/20-www.freecodecamp.dev.conf
=> feat: enable german client apps

sites-enabled/10-www.freecodecamp.org.conf, sites-enabled/15-chinese.freecodecamp.org.conf, sites-enabled/20-www.freecodecamp.dev.conf, sites-enabled/30-chinese.freecodecamp.dev.conf
This PR moves the chinese routing to supaths from subdomains
=> fix(chinese): move from subdomain to subpath

sites-enabled/15-chinese.freecodecamp.org.conf
=> fix(chinese): capture old forum for now

sites-enabled/11-api.freecodecamp.org.conf, sites-enabled/21-api.freecodecamp.dev.conf
Reverts freeCodeCamp/nginx-config#80
=> Revert "feat(api): add client IP to XFF"

sites-enabled/40-chapter.freecodecamp.org.conf, sites-enabled/50-chapter.freecodecamp.dev.conf
=> feat: redirect chapter. to www.

nginx.conf
This PR adds log format for collecting metrics we can injest using promtail to a Loki instance for use with Grafana dashboards later
=> feat: collect logs in Grafana's expected format

maps/legacy-301-redirects.map, maps/legacy-302-redirects.map
Checklist:
Should merge and deploy in tandem with https://github.com/freeCodeCamp/freeCodeCamp/pull/50960.
@raisedadead I hope I did this right? It should redirect: 
```txt
/learn/responsive-web-design/responsive-web-design-projects/build-a-tribute-page
/learn/2022/responsive-web-design/build-a-tribute-page-project/build-a-tribute-page
``` 
for example.
=> feat: add redirect for legacy RWD projects

maps/legacy-302-redirects.map
=> fix: rwd redirect needs /learn prefix

sites-enabled/20-www.freecodecamp.dev.conf
Add the staging news for testing.
=> feat: add staging jamstack sites

sites-enabled/10-www.freecodecamp.org.conf
=> feat: only enable the german client

nginx.conf, scgi_params, sites-enabled/10-www.freecodecamp.org.conf, sites-enabled/20-www.freecodecamp.dev.conf, sites-enabled/21-api.freecodecamp.dev.conf, snippets/common/add-noindex-headers.conf, snippets/common/proxy-params.azure.conf, snippets/common/proxy-params.conf, snippets/common/proxy-params.netlify.conf, snippets/common/ssl-freecodecamp-com.conf, snippets/common/ssl-freecodecamp-dev.conf, snippets/common/ssl-freecodecamp-org.conf, uwsgi_params
My editor trips me all the time. Formatting this for once!
=> chore: fix formatting forever

maps/legacy-302-redirects.map
=> fix: adjust shop url redirect
